apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data
  namespace: app
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi