name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lint all markdown files
        run: |
          make lint
