name: Deploy Rodeos

on:
  push:
    branches:
      - main
    paths:
    - 'Rodeos/**'

jobs:
  lint:
    name: Lint Rodeo Scenarios
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint all Rodeo markdown files
        run: |
          make lint-rodeos
  deploy:
    name: Deploy Scenarios to Hobbyfarm
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
         environment: [NA, EU]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install hfcli
        run: |
          wget https://github.com/hobbyfarm/hfcli/releases/download/0.1.0/hfcli_Linux_x86_64.tar.gz
          tar xvf hfcli_Linux_x86_64.tar.gz
          mv hfcli /usr/local/bin/hfcli
      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
          make apply-rodeos
